### ISSUE TITLE
Can't run app locally. npm start unexpected error

### ISSUE THREAD

**Issue by AndrewBMartin** [michelson/dante2#250]
Cloned dante2. Following the README. Ran `npm i` with no issues. Then `npm start` first got an error saying null needs to be installed, so `npm i --save null` and then when I run `npm start` again I get "TypeError: s is not a function" (error attached below). 

It seems the error is associated with building the docs, so if I remove the "docz" from `npm start` in package.json then I get an error with rollup where it says it needs a NODE_ENV. When I update package.json `dev` with a NODE_ENV for rollup, rollup starts without error, but I can't find the app running on localhost:8080 (or anywhere else).

Ultimately, want to run the app locally for development, but these errors are making it impossible.

`npm start` error

`/Users/andrewmartin/dante2/node_modules/docz-core/dist/index.js:1
"use strict";function _interopDefault(e){return e&&"object"==typeof e&&"default"in e?e.default:e}Object.defineProperty(exports,"__esModule",{value:!0});var fs=require("fs"),path=require("path"),resolve=_interopDefault(require("resolve")),prettier=require("prettier"),logger=_interopDefault(require("signale")),fs$1=require("fs-extra"),artTemplate=require("art-template"),crypto=require("crypto"),vfile=_interopDefault(require("to-vfile")),unified=_interopDefault(require("unified")),remark=_interopDefault(require("remark-parse")),matter=_interopDefault(require("remark-frontmatter")),slug=_interopDefault(require("remark-slug")),parseFrontmatter=_interopDefault(require("remark-parse-yaml")),slugify=_interopDefault(require("@sindresorhus/slugify")),find=_interopDefault(require("unist-util-find")),is=_interopDefault(require("unist-util-is")),visit=_interopDefault(require("unist-util-visit")),get=_interopDefault(require("lodash.get")),humanize=_interop`

`TypeError: s is not a function`

    at parseHtml (/Users/andrewmartin/dante2/node_modules/docz-core/dist/index.js:1:18796)
    at template (/Users/andrewmartin/dante2/node_modules/docz-core/dist/index.js:1:20834)
    at MiniHtmlWebpackPlugin.plugin (/Users/andrewmartin/dante2/node_modules/mini-html-webpack-plugin/index.js:17:33)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/andrewmartin/dante2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/andrewmartin/dante2/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/andrewmartin/dante2/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (/Users/andrewmartin/dante2/node_modules/webpack/lib/Watching.js:51:19)
    at hooks.afterCompile.callAsync.err (/Users/andrewmartin/dante2/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/andrewmartin/dante2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/andrewmartin/dante2/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/andrewmartin/dante2/node_modules/webpack/lib/Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/andrewmartin/dante2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/andrewmartin/dante2/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/andrewmartin/dante2/node_modules/webpack/lib/Compilation.js:1423:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/andrewmartin/dante2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/andrewmartin/dante2/node_modules/tapable/lib/Hook.js:154:20)

`error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c /Users/andrewmartin/dante2/node_modules/.bin/docz dev
Directory: /Users/andrewmartin/dante2
Output:  `

**Comment by michelson** [comment]
hi, try with `yarn install` & `yarn docz:dev`
